### ISSUE TITLE
configurable default timeouts and periods

### ISSUE THREAD

**Issue by mjpitz** [indeedeng/libhealth#1]
So I know in Java we allowed folks to configure timeouts and periods. What's the recommended way to go about doing that in the go version of status? I just got bit by the default 30s interval in a kubernetes pod... would be good to be able to configure the defaults in some way.

**Comment by mjpitz** [comment]
@cnmcavoy any recommendations here? I don't mind implementing the interface myself, but it would be nice if this was able to be done out of box.

**Comment by cnmcavoy** [comment]
`libhealth.NewMonitor(...)` [applies the defaults](https://github.com/indeedeng/libhealth/blob/main/monitor.go#L36):

```
	defaultTimeout = 60 * time.Second
        defaultPeriod  = 30 * time.Second
```

```
func NewMonitor(
...
) *Monitor {
	return &Monitor{
		name:        name,
		timeout:     defaultTimeout,
		period:      defaultPeriod,
...
	}
}
```

Unfortunately, while the `Monitor` struct is exported, the fields are not. The simplest change I think would be exposing a separate constructor to set the timeout and period.

**Comment by mjpitz** [comment]
Alright, I pushed up a PR for allowing these values to be configurable. Let me know if you have any feedback :-)

**Comment by cnmcavoy** [comment]
thanks!
