### ISSUE TITLE
https://oss.indeed.com/go is 503'ing

### ISSUE THREAD

**Issue by joeyparsons** [indeedeng/libhealth#5]
Not sure where else to report this but `oss.indeed.com/go` is 503'ing, including `libhealth`  Failing a bunch of mod installs for me -- can someone take a look?

**Comment by jdroot** [comment]
Sorry about that! I can look in to it

**Comment by jdroot** [comment]
@joeyparsons Sorry for the slow response here, but can you verify that the issue has been fixed?

**Comment by joeyparsons** [comment]
@jdroot thanks so much, just got around to re-adding to my app.  works great now, thank you!
